<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
		<PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.3.36726.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Gravel\Gravel.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Tier1Hotpath\" />
	  <Folder Include="Tier3System\" />
	</ItemGroup>

</Project>